
spring:
  datasource:
    url: jdbc:mysql://aws-mysql.bookstore.rds.amazonaws.com:3306/bookstore?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: kim0821pg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

